# Generated by Django 3.2.23 on 2024-11-03 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle_routing", "0002_rename_litre_retail_price_gasstation_liter_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gasstation",
            old_name="liter_price",
            new_name="retail_price",
        ),
    ]
