# Generated by Django 3.2.23 on 2024-10-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TruckStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("state_code", models.CharField(max_length=3)),
                ("postal_code", models.CharField(max_length=10)),
                ("position_latitude", models.FloatField()),
                ("position_longitude", models.FloatField()),
                ("here_map_id", models.CharField(max_length=255)),
                ("litre_retail_price", models.FloatField()),
            ],
        ),
        migrations.AddIndex(
            model_name="truckstop",
            index=models.Index(
                fields=["here_map_id"], name="truck_routi_here_ma_01f534_idx"
            ),
        ),
    ]
